### PR TITLE
Update Company.all to use the newer Hubspot endpoint

### PR DESCRIPTION
**Pull request by sam2themax**
This addresses Issue #75 that I opened a little while ago.

Updated `Hubspot::Company.all` to use the new endpoint described at https://developers.hubspot.com/docs/methods/companies/get-all-companies

I renamed the existing `Hubspot::Company.all` method to `Hubspot::Company.recent` because that's what the new endpoint structures seem to indicate is the function.

**Note that this would be a non-backwards-compatible change if it's accepted because the return structure is different in my new `all` method.**

### CODE REVIEW

**Comment by cbisnett** [comment]
This looks like a good change to me, but like you pointed out this change is not backwards compatible. I think we should hold off on adding this until the v1.0.0 branch. I hope to get some more of the outstanding pull requests merged and get some other fixes in there and then release in a few weeks.

**Comment by kitebuggy** [comment]
Thank you both - saves me a pull request.  :-)
Any ETA on v1 ?

**Comment by cbisnett** [comment]
Getting started on the 1.x branch will happen relatively soon (week or so) but actually releasing a new gem won't come for a while. There are a bunch of smallish things that need to be cleaned up and made uniform across the codebase before releasing. If we don't get to those then they will have to wait until 2.x because they will again break backwards compatibility.

**Comment by sam2themax** [comment]
@cbisnett Hi Chris, curious if anything ever came of the 1.x branch or if there's any chance of getting this merged at some point.  My development team is currently needing to improve our hubspot integration in a major way, and it looks like the Hubspot APIs have changed quite a bit in the last year or two.

**Comment by cbisnett** [comment]
Instead of making a branch for the 1.x version we made branch v0-stable to track the old code as we continue to refactor and update the master branch. I've already made some significant changes to the library interface works which included splitting recently created/modified queries into their own functions separate from the all companies query. Now that most of the foundation is completed, the remaining work is progressing pretty quickly.

**Pull request closed without merging**
