### PR TITLE
Update gem dependencies for json and webmock

### PR DESCRIPTION
**Pull request by mpapis**
- fixes the 4 following tests
    ```bash
    rspec ./spec/lib/hubspot/contact_spec.rb:60 # Hubspot::Contact.createOrUpdate with a new email
    rspec ./spec/lib/hubspot/contact_spec.rb:61 # Hubspot::Contact.createOrUpdate with a new email email
    rspec ./spec/lib/hubspot/contact_spec.rb:67 # Hubspot::Contact.createOrUpdate with a new email and some params firstname
    rspec ./spec/lib/hubspot/contact_spec.rb:68 # Hubspot::Contact.createOrUpdate with a new email and some params lastname
    ```

### CODE REVIEW

**Comment by dan987** [comment]
There is another pr that solves this problem by removing the gemfile.lock https://github.com/adimichele/hubspot-ruby/pull/85.

**Comment by mpapis** [comment]
the `webmock` dependency still needs updating, I can rebase it on master after #85 is merged and push just this fix with only `webmock` updated.

**Comment by cbisnett** [comment]
Since #85 has been merged is this something that still needs to be done?

**Comment by mpapis** [comment]
Yes, on master the specs are still failing with above errors, after updating those failures are gone.

There is another failure on master now, but as I'm not more involved with using the lib, I got no time to fix it. I would suggest setting up travis-ci.org or other CI to prevent merging PR's breaking master.

**Comment by cbisnett** [comment]
Dependencies have been updated and tests are passing on master. Closing this PR as the issue it references is fixed.

**Pull request closed without merging**
