### PR TITLE
Add Logging for Request/Response. Implement Contact Properties & Group API calls. Update Forms API to V2.

### PR DESCRIPTION
**Pull request by srgoldman**
Fixed find_by_email to behave according to the documentation. Implemented batch results.
Added request/response logging
Implemented ContactProperties APIs
Dump/Restore rake tasks to backup schema changes and make it easy to apply changes from one environment to another.
Added a bunch of tests.

### CODE REVIEW

**Comment by dan987** [comment]
Any updates on this, is @adimichele still working with this?

**Comment by srgoldman** [comment]
Not that I’m aware of. I haven’t seen any activity other than mine. You’re welcome to fork my fork :-).

**Comment by adimichele** [comment]
We stopped using Hubspot and I stopped maintaining this years ago. Would either of you like to take over?

**Comment by dan987** [comment]
thanks for the fast reply @adimichele....  @srgoldman looks like you have put some time in with this, you should take it if you want.  If not I would be willing, as I will be working with this quite a bit in the future....  Also @adimichele was there problems with hubspot?

**Comment by srgoldman** [comment]
@dan987 - I don't have a strong preference. I've been adding features as necessary but it's not particularly active development for us right now. It sounds like you have a more urgent need and would therefore be a more motivated custodian. I'm happy to let you have it and continue to contribute as needed. I actually have additional changes that I hadn't yet put into a PR which enable the gem to register its rake tasks in an including rails app. And @adimichele - A belated thanks for the initial groundwork which made my life much easier!

**Comment by dan987** [comment]
@adimichele yes thank you for this, sounds like a pass from @srgoldman.  I would be happy to take over as needed.

**Comment by srgoldman** [comment]
FYI - I’m doing some work on the Forms API at the moment, upgrading it to V2.

Seth Goldman
FlashFunders Engineering
www.flashfunders.com <http://www.flashfunders.com/>

seth@flashfunders.com
310-729-4506

**Comment by adimichele** [comment]
Cool! @dan987 I made you a collaborator so you should have push perms now. I need to make you an owner on RubyGems as well - which email address would you like me to use for that?

**Pull request merged**
