### PR TITLE
Allow creating or updating in batches

### PR DESCRIPTION
**Pull request by yurikoval**
API Docs: https://developers.hubspot.com/docs/methods/contacts/batch_create_or_update

### CODE REVIEW

**Comment by anna51100** [comment]
Love it! Can't wait to see it merged!

**Comment by ManuelFrigerio** [comment]
Why this hasn't been merged yet?
Given Hubspot 10K/day limit, this feature would make this gem AWESOME!

**Comment by yurikoval** [comment]
@adimichele I've fixed the conflicts

**Comment by yurikoval** [comment]
@dan987 @adimichele I've fixed the conflicts

**Pull request merged**
