### PR TITLE
WIP - Feature/webhook

### PR DESCRIPTION
**Pull request by pifleo**

### CODE REVIEW

**Comment by dan987** [comment]
@pifleo would love to merge this in, can you provide some context around the WIP?

**Comment by pifleo** [comment]
Hey @dan987 !

It’s a mistake, I thought this PR was open on my fork and not on the main repository.

I’m working on an implementation of the webhooks with @fonji. We are really at the firsts steps on this and met many difficulties (We are asking a lot of questions on the forum: https://integrate.hubspot.com/search?q=fonji).

This gem doesn’t implement Oauth, so we are working on that and then classes and actions for the `Webhooks` and `Timeline` endpoints.

So, some steps:

  - Oauth token generation and reset (Maybe a controller)
  - Actions for webhooks in the gem + specs
  - ... surprises from the documentation and endpoints ???

**/!\ This PR includes many modification of the initial gem as we implemented and merged many PR from other people as you can see here: https://github.com/captaincontrat/hubspot-ruby/commits/master.**

I’m closing it here, and will work on it on my fork: https://github.com/captaincontrat/hubspot-ruby/pull/3. We will propose a new clean PR here when it will be ready and tested! You can help us work on that ;)

**Comment by dan987** [comment]
@pifleo sounds great, there are a few older things in the pr that we need here besides oauth & webhooks that I was working on.  Would love to get them on this copy the gem now.

**Comment by pifleo** [comment]
@dan987 you can use the gem directly from the repo with `gem 'hubspot-ruby', github: 'captaincontrat/hubspot-ruby' # https://github.com/adimichele/hubspot-ruby` in your `Gemfile`
You will need to bundle to get the last commits.

**Pull request closed without merging**
