### PR TITLE
Sort blog posts by publish date

### PR DESCRIPTION
**Pull request by supremebeing7**
Fixes https://github.com/adimichele/hubspot-ruby/issues/34

### CODE REVIEW

**Comment by dan987** [comment]
Have not used the api for blog posts, does anyone else have an opinion on this PR?

**Comment by adimichele** [comment]
I don't think we should make his change since it will break any user code that depends on the current default sort order.

**Comment by supremebeing7** [comment]
That's fair. Would it make sense it make the change as part of the next minor version (i.e. 0.2.0)?

The impetus for this change was that the current implementation seemed a bit counter-intuitive to me. If I'm the only one, though, I can close this and stop bothering you 😄

**Comment by cbisnett** [comment]
Looking at the HubSpot documentation, I can't tell if ordering by `created` works. The [documentation](https://developers.hubspot.com/docs/methods/blogv2/get_blog_posts) for the `order_by` parameter only supports `publish_date`:
> Blog posts can currently only be sorted by publish_date.

I think these default settings are sane, although for specific implementations I can understand specifying different sorting. If there are others that are also looking for this change we can make it, but we'll need to bump the version and give users ample time to update their implementations so we don't surprise them.

**Comment by supremebeing7** [comment]
@cbisnett You're right. It's been awhile since I looked at this, but trying to order by `created` gave exactly the same results as not ordering at all, so I don't think that is a supported param. 

I do still think ordering by publish date makes the most sense but definitely don't want to introduce breaking changes for folks who depend on this gem. I'll leave my branch up -- if others out there in the wild stumble on this and it reaches critical mass we can reopen, but until then it's easy enough to pass in the order by parameter.

**Pull request closed without merging**
